# Generated by Django 3.2.3 on 2021-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='nombre',
            field=models.CharField(max_length=35, verbose_name='Nombre Completo'),
        ),
    ]
