# Generated by Django 3.2.3 on 2021-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_auto_20210611_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencista',
            name='experiencia',
            field=models.TextField(null=True),
        ),
    ]
