# Generated by Django 3.2.3 on 2021-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0005_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='conferencista',
        ),
        migrations.AddField(
            model_name='conferencia',
            name='conferencista',
            field=models.ManyToManyField(blank=True, to='app_registro.Conferencista'),
        ),
    ]
