# Generated by Django 3.2.3 on 2021-06-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0007_auto_20210616_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='particpante',
            new_name='participante',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('conferencia', 'participante')},
        ),
    ]
